### PR TITLE
Add field JobReportFormatter<String> formatter help dev can customize…

### PR DESCRIPTION
**Pull request by vudangngoc**
… report toString()

### CODE REVIEW

**Comment by benas** [comment]
Hi, thank you for this PR!

Do you think we need to make the formatter configurable *inside the report* ?

We can use a custom formatter directly:

```
String result = new MyCustomFormatter().format(jobReport);
```

instead of:

```java
String result = jobReport.toString();
```

Do you agree?

**Comment by vudangngoc** [comment]
I think
`String result = MyCustomFormatter.format(jobReport);`
is better than
`String result = new MyCustomFormatter().format(jobReport);`
because we don't have to create new object, GC will have less job to do.
About my PR, I have just try to use EasyBatch and didn't aware about easybatch-tools. So that I created this PR. I think the both ways are the same. In my case, I directly send JobReport object to Spring RESTful webservice and Spring automatically create JSON object from that. 
But toString() with default formatter really make me confuse.

**Comment by benas** [comment]
> I think
> String result = MyCustomFormatter.format(jobReport);
> is better than
> String result = new MyCustomFormatter().format(jobReport);
> because we don't have to create new object, GC will have less job to do.

Yes yes of course, that was just a quick example to show how we can use a custom formatter outside the report. Now that you are aware of the tools module, you've got the idea.

> In my case, I directly send JobReport object to Spring RESTful webservice and Spring automatically create JSON object from that.

Is the toString method of the report used in the JSON marshalling process?

> But toString() with default formatter really make me confuse.

Before using the default formatter in toString, there was a code duplication:

* formatting code in the toString method (which is wrong, it's not the role of the report to format data)
* same formatting code in the DefaultFormatter (in the tools module)

to fix these issues, I moved the default formatter to the core module and delegated formatting to the default formatter (See fcf13472be002fcfdfe8e7447e68330444e0ef1a).

Does this make sense to you?

I'm not sure I understand why it's confusing to you. The default toString method uses the default formatter. If you need a custom formatter, you can use the JobReportFormatter API specifically designed for this.

**Comment by vudangngoc** [comment]
As I said before: "I think the both ways are the same" and "I have just try to use EasyBatch and didn't aware about easybatch-tools"

> Is the toString method of the report used in the JSON marshalling process?

I didn't deeply dig at Spring, but I think it doesn't.

> I'm not sure I understand why it's confusing to you
I think toString() will give representation about JobReport object, without formatting :)

**Pull request closed without merging**
