### PR TITLE
Adding uniVocity support

### PR DESCRIPTION
**Pull request by AussieGuy0**
This pull request adds a uniVocity extension so that CSV, TSV and Fixed Width Formats can be mapped and marshalled.

### CODE REVIEW

**Comment by benas** [comment]
Hello Anthony,

Fantastic! That's great 👍 This is what we call a very high quality pull request 😄 
Nothing to say, straight to the master branch.
Many thanks, I really appreciate your help.

Keep the good work up on univocity!
I'll not hesitate to give you credits.

Best regards
Mahmoud

**Comment by benas** [comment]
Hi Anthony,

The build is failing on windows (I have to add a CI for windows in addition to mac/linux, travis-ci does not support windows yet..).

The following tests are failing:

1. UnivocityRecordMarshallerTest#processRecordIntoCsv
2. UnivocityRecordMarshallerTest#processRecordIntoTsv
3. UnivocityRecordMarshallerTest#processRecordIntoFixedWidth
4. UnivocityRecordMapperTest#testUnivocityCsvCarriageReturn

I have already fixed 1, 2 and 3 by replacing "\n" with Utils.LINE_SEPARATOR. I'll push the fix asap.

For the 4th test, it seems like the CsvParser converts "\r\n" to "\n". Here is a failing test that isolates the problem:

```java
    @Test
    public void testUnivocityCsvCarriageReturnLineFeed() throws Exception {
        BeanListProcessor<TestBean> beanListProcessor = new BeanListProcessor<>(TestBean.class);
        CsvParserSettings csvParserSettings = new CsvParserSettings();
        csvParserSettings.getFormat().setQuote('\'');
        csvParserSettings.setProcessor(beanListProcessor);

        CsvParser parser = new CsvParser(csvParserSettings);
        String payload = "'foo" + LINE_SEPARATOR + "','bar" + LINE_SEPARATOR + "'";
        parser.parse(new StringReader(payload));

        TestBean result = beanListProcessor.getBeans().get(0);
        assertThat(result).isNotNull();
        assertThat(result.getFirstName()).isEqualTo("foo" + LINE_SEPARATOR);
        assertThat(result.getLastName()).isEqualTo("bar" + LINE_SEPARATOR);
    }
```

I tried to set some options:

```java
csvParserSettings.setDelimiterDetectionEnabled(true);
csvParserSettings.setQuoteDetectionEnabled(true);
csvParserSettings.setLineSeparatorDetectionEnabled(true);
```

but it still failing. The `payload` variable on windows contains `'foo\r\n','bar\r\n'` but `result.getFirstName()` is equal to `foo\n`. Any idea?

Kr
Mahmoud

**Comment by benas** [comment]
Oh thanks! I tried both of these changes and it is still failing.

I'll continue investigating on my side. Let me know if you find something interesting.

Kr
Mahmoud

**Comment by benas** [comment]
I have updated tests to ignore os specific line endings, but still, I'm curious to know why this is failing on windows..

**Comment by AussieGuy0** [comment]
Hey mate,

Found the problem. You need to add the following code:

```java
csvParserSettings.setNormalizeLineEndingsWithinQuotes(false);
```

Basically, uniVocity will replace a detected line separator that is within quotes with whatever the normalized line separator (default is `\n`). This is to prevent blank lines being added when dealing with the same data on different platforms. By adjusting this setting to false, the `\r\n` will be retained in the test code.

Hope this solves everything. If you have any more questions, feel free to ask! Altough you owe me for making be boot into Windows 😉

**Comment by benas** [comment]
I came across this setting and set it to true (not false).. Now it is more clear to me.

Thank you for your time!

**Pull request merged**
